server:
  port: 8000
spring:
  application:
    name: Agenda Digital Escolar
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:agenda-digital-escolar
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  data:
    jdbc:
      dialect: h2